CREATE DATABASE IF NOT EXISTS BD_ALUGUEL;
USE BD_ALUGUEL;

CREATE TABLE IF NOT EXISTS CLIENTE(
	CLI_ID INT AUTO_INCREMENT PRIMARY KEY,
    CLI_NOME VARCHAR(50) NOT NULL,
    CLI_CPF VARCHAR(11)NOT NULL,
    CLI_EMAIL VARCHAR(50)NOT NULL,
    CLI_TELEFONE VARCHAR(9) NOT NULL
);
ALTER TABLE CLIENTE 
MODIFY COLUMN CLI_CPF VARCHAR(11)NOT NULL UNIQUE;

CREATE TABLE IF NOT EXISTS PRODUTO(
	PRO_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRO_NOME VARCHAR(50) NOT NULL,
    PRO_DESCRICAO VARCHAR(200),
    PRO_PRECO DOUBLE NOT NULL,
    PRO_QTD_DISPONIVEL INT NOT NULL
);

CREATE TABLE IF NOT EXISTS ALUGUEL(
	ALU_ID INT AUTO_INCREMENT PRIMARY KEY,
    ALU_DATA_ALUGUEL DATE NOT NULL,
    ALU_DATA_DEVOLOCAO DATE NOT NULL,
    ALU_VALOR_TOTAL DOUBLE NOT NULL,
    FK_CLI_ID INT,
    FOREIGN KEY (FK_CLI_ID) REFERENCES CLIENTE(CLI_ID)
);
CREATE TABLE IF NOT EXISTS ALUGUEL_PRODUTO(
	ALP_ID INT AUTO_INCREMENT PRIMARY KEY,
    FK_PRO_ID INT NOT NULL,
    FK_ALU_ID INT NOT NULL,
    FOREIGN KEY (FK_PRO_ID) REFERENCES PRODUTO(PRO_ID),
	FOREIGN KEY (FK_ALU_ID) REFERENCES ALUGUEL(ALU_ID)
);

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Pedro","53791710877","pedro@email.com","989956375");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Ana lara","00000000000","Ana@email.com","999999999");

SELECT * FROM CLIENTE;

INSERT INTO PRODUTO (PRO_NOME, PRO_PRECO, PRO_QTD_DISPONIVEL )
VALUES ("CELULAR","589.90","100");

SELECT * FROM PRODUTO;

INSERT INTO PRODUTO (PRO_NOME, PRO_DESCRICAO, PRO_PRECO, PRO_QTD_DISPONIVEL )
VALUES ("LANCHA TURBO","PARA RIO E MAR","589.90","100");

SELECT * FROM PRODUTO;

INSERT INTO ALUGUEL (ALU_DATA_ALUGUEL, ALU_DATA_DEVOLOCAO, ALU_VALOR_TOTAL,FK_CLI_ID )
VALUES ("2026-10-08","2026-10-15","600.89","2");

SELECT * FROM ALUGUEL;

INSERT INTO ALUGUEL_PRODUTO (FK_PRO_ID,FK_ALU_ID )
VALUES (1,1);

SELECT * FROM ALUGUEL_PRODUTO;

-- CLIENTE --

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("ANA SILVA","12345678900","Ana.silva@exemple.com","123456789");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("bruno souza","23456789100","bruno.souza@exemplo.com","345678910");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("carla mendes","34567891020","carla.mendes@exemplo.com","456789123");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("daniel rocha","45678912300","daniel.rocha@exemplo.com","567891234");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("elaine costa","56789123400","elaine.costa@exemplo.com","678912345");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("felipe lima","67891234500","felipe.lima@exemplo.com","789123456");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("giseli martins","78912345600","geseli.martins@exemplo.com","891234567");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("henrique alves","89123456700","henrique.alves@exemplo.com","912345678");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("isabela ferreira","91234567800","isabela.ferreira@exemplo.com","912345678");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("joão oliveira","10234567890","joão.oliveira@exemplo.com","789456123");

SELECT * FROM CLIENTE;

-- PRODUTO --

INSERT INTO PRODUTO (PRO_NOME, PRO_DESCRICAO, PRO_PRECO, PRO_QTD_DISPONIVEL )
VALUES ("Notebook dell inspirion","Notebook com processador intel core i7, 16GB de RAM 512GB SSD","450","10");

INSERT INTO PRODUTO (PRO_NOME, PRO_DESCRICAO, PRO_PRECO, PRO_QTD_DISPONIVEL )
VALUES ("smartphone samsansug galaxy s21","smartphone com tela de 6.2 polegadas,128GB de armazenamento","350","15");

INSERT INTO PRODUTO (PRO_NOME, PRO_DESCRICAO, PRO_PRECO, PRO_QTD_DISPONIVEL )
VALUES ("TV LG 55 4K","Smart TV com resolução 4K e HDR","280","8");

INSERT INTO PRODUTO (PRO_NOME, PRO_DESCRICAO, PRO_PRECO, PRO_QTD_DISPONIVEL )
VALUES ("Drone Djl Phantom 4","Drone com câmera 4k e estabilização de imagem","300","55");

INSERT INTO PRODUTO (PRO_NOME, PRO_DESCRICAO, PRO_PRECO, PRO_QTD_DISPONIVEL )
VALUES ("câm. canon EOSI T7","camera DSLR com lente 18-55mm, 24.1MP","25","2");

INSERT INTO PRODUTO (PRO_NOME, PRO_DESCRICAO, PRO_PRECO, PRO_QTD_DISPONIVEL )
VALUES ("camera Gopro hero 9 ","Camera de ação com relação 5k e resistente a água","80","60");

INSERT INTO PRODUTO (PRO_NOME, PRO_DESCRICAO, PRO_PRECO, PRO_QTD_DISPONIVEL )
VALUES ("tenda evento 5x5 ","Tenda resistente á agua e facil de montar ","200","4");

INSERT INTO PRODUTO (PRO_NOME, PRO_DESCRICAO, PRO_PRECO, PRO_QTD_DISPONIVEL )
VALUES ("microfone Shure SM58","Microfone para apresentação e shows","40","35");

INSERT INTO PRODUTO (PRO_NOME, PRO_DESCRICAO, PRO_PRECO, PRO_QTD_DISPONIVEL )
VALUES ("Mesa de som behringer","mesa de som com 16 canais e efeitos entegrados","500","3");

INSERT INTO PRODUTO (PRO_NOME, PRO_DESCRICAO, PRO_PRECO, PRO_QTD_DISPONIVEL )
VALUES ("kit de iluminação fotografica","kit com softbox, tripes e lampadas de LED","100","6");

SELECT * FROM PRODUTO;
SELECT PRO_NOME, PRO_DESCRICAO FROM PRODUTO;
SELECT PRO_NOME, PRO_DESCRICAO, PRO_PRECO FROM PRODUTO;

-- SELECIONAR APENAS PRODUTOS COM PREÇO MAIOR DE 250 --

SELECT * FROM PRODUTO
WHERE PRO_PRECO > 250;

-- SELECIONAR APENAS PRODUTO DE ID = 3 --

SELECT * FROM PRODUTO
WHERE PRO_ID = 3;

SELECT PRO_ID, PRO_NOME FROM PRODUTO
WHERE PRO_ID = 3;

-- SELECIONAR TODOS OS PRODUTOS QUE CONTENHAM NOTEBOOK EM QUALQUER PARTE DO NOME --

SELECT * FROM PRODUTO
WHERE PRO_NOME LIKE '%NOTEBOOK%';

-- ATUALIZAR QUANTIDADES DE NOOTEBOOK PARA 200 -- 

UPDATE PRODUTO
SET PRO_QTD_DISPONIVEL = 200
WHERE PRO_ID = 1; -- UPDATE TEM QUE TER WHERE --

SELECT * FROM PRODUTO;

-- APAGAR (DELETAR) O NOTEBOOK
DELETE FROM PRODUTO 
WHERE PRO_ID = 1; -- DELETE TEM QUE TER WHERE 

 







