CREATE DATABASE IF NOT EXISTS BD_MUSICA;
USE BD_MUSICA;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(100)  NOT NULL,
   TELEFONE VARCHAR(11) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    ESTILO VARCHAR(100)  NOT NULL,
    GENERO VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TIPO_DE_MUSICA INT NOT NULL,
    FK_CPF_ARTISTA VARCHAR(11)
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    CARACTERISTICAS VARCHAR(100) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    FK_ID_ALBUM VARCHAR(11),
	FK_ID_GENERO VARCHAR(11)
);



